### ISSUE TITLE
Working with Jest

### ISSUE THREAD

**Issue by mtoso** [graphcool/graphql-import#146]
Hello thanks for this work. I am trying to to run tests with Jest but they are failing when i have an import statement inside my schema to import another graphql type def.
Any suggestions?

Thanks

**Comment by engfragui** [comment]
Example:

In `data-sources/data-source-1/schema1.graphql`, at the beginning of the schema:
`# import { ImportedType } from 'data-sources/data-source-2/schema2.graphql'`

All good when running our graphql server (server runs from `/Users/<user>/Projects/graphql-data-sources` and the import is resolved correctly as `/Users/<user>/Projects/graphql-data-sources/data-sources/data-source-2/schema2.graphql`).

Issue when running Jest tests:

`
FAIL  data-sources/data-source-1/__tests__/schema1.test.ts
  ● Data Source 1 schema › encountered a declaration exception

    ENOENT: no such file or directory, open '/Users/<user>/Projects/graphql-data-sources/data-sources/data-source-1/data-sources/data-source-2/schema2.graphql'

       5 |
       6 | describe('Data Source 1 schema', () => {
    >  7 |   const typeDefs = importSchema(
       8 |     resolve(__dirname, '..', 'schema1.graphql'),
       9 |   );
      10 |
`

The issue is fixed if we change the import to:
`# import { ImportedType } from '../data-source-2/schema2.graphql'`

so that the path that Jest tries to go to is `/Users/<user>/Projects/graphql-data-sources/data-sources/data-source-1/../data-source-2/schema2.graphql`, but then when we run the server the import is not working correctly anymore since it tries to resolve to `/Users/<user>/Projects/graphql-data-sources/../data-source-2/schema2.graphql` which doesn't exist.

This seems related to the fact that the tests run a different location compared to the location from which the server runs. Any suggestions to make both work?

Thank you

**Comment by kMeillet** [comment]
You can try this : https://github.com/kMeillet/jest-graphql-import

Copy "jestGraphql.js" into your project and Jest configuration in "package.json" with new transformer : 

```
  "jest": {
    "transform": {
      "\\.(gql|graphql)$": "./jestGraphql.js",
      ".*": "babel-jest"
    }
```

**Comment by engfragui** [comment]
Thank you @kMeillet. Unfortunately the transformer didn't help.
However, jest is able to correctly resolve the import in our graphql schema if the path in the import makes sense from the test folder.

If this is the import:
`
# import { SomeType } from '../data-source-2/schema2.graphql'
`
then the tests work, so it looks like importSchema is working correctly. 

Our issue is that the relative path that makes the tests work (`'../data-source-2/schema2.graphql'`) messes up the server which doesn't work anymore since it cannot find the relative path from its starting location.

**Comment by engfragui** [comment]
I was able to make this work by replacing 

`
const typeDefs = importSchema( resolve(__dirname, '..', 'schema2.graphql'), );
`

with 

`
const typeDefs = require('../schema2.graphql');
`

in my jest test and using @kMeillet's `transformer.js`.

Thank you @kMeillet! 🍻
