### ISSUE TITLE
Import is not required in graphql-yoga schema definition

### ISSUE THREAD

**Issue by divyenduz** [graphcool/graphql-import#59]
I was working on a project that started from the boilerplate and hence my schema has the following line at the top

`# import Post from "./generated/prisma.graphql"`

Initially, I mistook this for a comment (because #, coloring from my editor) but later I ran into `graphql-import` and understood that this is an import. 

What I noted was that import is not required as I am able to use other types from `prisma.graphql` without having to import them explicitly. 

Is this behavior expected? I spoke to @marktani about it and he recommended that I should raise the issue here. 

A snippet of my schema.graphql would look like this

```
# import Post from "./generated/prisma.graphql"

type Query {
  getUser(id: ID!): User
  getPost(id: ID!): Post
}
```

Notice that I have only imported Post from `prisma.graphql` but I am able to use User as well without explicitly importing it.

**Comment by kbrandwijk** [comment]
This might work because `graphql-import` detects missing types. So because you import `Post` from `prisma.graphql`, it will also import other missing types you use in your schema. This is a side effect of the logic that detects types used in your imported types (so if Post uses another field type, it will import that as well). If you remove the line completely, it won't work anymore.

**Comment by marktani** [comment]
One more thought is that `Post` has a relation to `User`, so importing the `Post` type will also import `User` because of the `author: User` field on `Post`.

If you'd add a new type `MyType` that has no relation to `User` or `Post`, and your `schema.graphql` looks like this:

```graphql
# import Post from "./generated/prisma.graphql"

type Query {
  getUser(id: ID!): User
  getPost(id: ID!): Post
  getMyType(id: ID!): MyType
}
```

would you then get an error?

**Comment by kbrandwijk** [comment]
Very good @marktani, that seems way more plausible.

**Comment by divyenduz** [comment]
Yes, indeed, in my case Post touches everything else. Your explanation explains the behavior I am running into and I can confirm that MyType (independent of Post) results in an error. 

Thanks for sorting this out for me @marktani and @kbrandwijk. 

Closing this one.
